# Site settings
title: SurfaceW
email: surfacew@163.com
description: "Little Dots accumulated to make a Difference."
baseurl: ""
url: "http://www.surfacew.com"
twitter_username: yeqingnan
github_username:  SurfaceW

# Build settings
markdown: kramdown
permalink: pretty
