# Site settings
title: SurfaceW
email: surfacew@163.com
description: "Here, I got to set up this site to share the dots with your guys. Hope you can get something nice here~"
baseurl: ""
url: "http://www.surfacew.com"
twitter_username: yeqingnan
github_username:  SurfaceW

# Build settings
markdown: kramdown
permalink: pretty
